version: "3.9"

services:
  backend:
    build:
      context: ./backend
    environment:
      - PYTHONPATH=/app  # Configure PYTHONPATH
      - NLTK_DATA=/usr/share/nltk_data  # Inclut les données NLTK
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./tests:/app/tests

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules