version: "3.9"

services:
  backend:
    image: akhkanda/classification-spam-app:backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./tests:/tests

  frontend:
    image: akhkanda/classification-spam-app:frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules