name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - staging
      - production

jobs:
  integration-tests:
    if: github.event_name == 'pull_request' && github.base_ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest

      - name: Run integration tests
        run: |
          cd tests
          pytest integration_test.py

  staging-tests:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for services to be ready
        run: |
          npx wait-on http://localhost:3000 http://localhost:5000

      - name: Run unit tests
        run: |
          cd tests
          pytest unit_test.py

      - name: Run Cypress end-to-end tests
        run: |
          cd tests/cypress
          npx cypress run

      - name: Stop services
        if: always()
        run: |
          docker-compose down

  build-and-deploy:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t my-app-backend:latest ./backend
          docker build -t my-app-frontend:latest ./frontend
          docker tag my-app-backend:latest ${{ secrets.DOCKER_USERNAME }}/my-app-backend:latest
          docker tag my-app-frontend:latest ${{ secrets.DOCKER_USERNAME }}/my-app-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app-frontend:latest
