name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - staging
      - production

jobs:
  integration-tests:
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'develop' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version 

      - name: Debug: List test files
        run: docker-compose run --rm backend ls -R /tests

      - name: Run integration tests
        run: |
          docker-compose run --rm backend pytest /tests/integration_test.py