name: Dev to Sta

on:
  push:
    branches:
      - develop

jobs:
  merging-to-sta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge develop into staging
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout staging
          git merge origin/develop --no-ff --commit -m "Merge develop into staging"
          git push origin staging
