name: CI/CD Pipeline

on:
  push:
    branches:
      - staging
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  staging-tests:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version

      - name: Install dependencies
        run: npm install cypress

      - name: Install GPU dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libnss3 x11-utils

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d

      - name: Run Cypress end-to-end tests
        uses: cypress-io/github-action@v5
        with:
          spec: tests/cypress/e2e/**/*.cy.js
          config-file: tests/cypress.config.js
          browser: chrome

      - name: Stop services
        if: always()
        run: docker-compose down

      - name: Merge staging into main
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout main
          git merge origin/staging --no-ff --commit -m "Merge staging into main"
          git push origin main

  integration-tests:
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version

      - name: Run integration tests
        run: |
          docker-compose run --rm backend pytest /tests/integration_test.py

  merge-to-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge develop into staging
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout staging
          git merge origin/develop --no-ff --commit -m "Merge develop into staging"
          git push origin staging

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version

      - name: Build services with Docker Compose
        run: |
          docker-compose build

      - name: Tag images
        run: |
          docker tag ml-in-prod_backend:latest ${{ secrets.DOCKER_USERNAME }}/classification-spam:backend-latest
          docker tag ml-in-prod_frontend:latest ${{ secrets.DOCKER_USERNAME }}/classification-spam:frontend-latest

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/classification-spam:backend-latest
          docker push ${{ secrets.DOCKER_USERNAME }}/classification-spam:frontend-latest
