name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - staging
      - production

jobs:
  integration-tests:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version

      - name: Build and Start Services
        run: |
          docker-compose up -d --build

      - name: Debug volume mounting
        run: |
          docker-compose run --rm backend ls /app

      - name: Run integration tests
        env:
          PYTHONPATH: /app
        run: |
          docker-compose run --rm backend pytest /app/tests/integration_test.py

      - name: Stop services
        if: always()
        run: |
          docker-compose down --remove-orphans
