name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  integration-tests:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version  # Vérification que docker-compose est installé

      - name: Run integration tests
        run: |
          docker-compose run --rm backend pytest /tests/integration_test.py

      - name: Merge develop into staging
        if: success()  
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout staging
          git merge origin/develop --no-ff --commit -m "CI: Merge develop into staging after integration tests"
          git push origin staging

  staging-tests:
    runs-on: ubuntu-latest
    needs: integration-tests 
    if: ${{ always() }}  # Toujours exécuter après les tests d'intégration
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version  

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for backend to be ready
        run: |
          npx wait-on http://localhost:3000
          
      - name: Run unit tests
        run: |
          docker-compose exec -T backend pytest /tests/unit_test.py
      
      - name: Run Cypress end-to-end tests
        run: |
          cd tests/cypress
          npx cypress run --config-file app/tests/cypress.config.js --headless

      - name: Stop services
        if: always()
        run: |
          docker-compose down
